apiVersion: app/v1
kind: Deployment
metadata:
  name: deployment-toko-baju
spec:
  replicas: 3
  selector:
    matchLabels:
      app: toko-baju
  template:
    metadata:
      labels:
        app: toko-baju
    spec:
      containers:
      - name: nginx
        image: nginx:1.21
        ports:
        - containerPort: 80