apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql-abadi     
  labels:
    app: database-saya
spec:
  containers:
  - name: mysql
    image: mysql:5.7
    env:
      - name: MYSQL_ROOT_PASSWORD
        valueFrom:
          secretKeyRef:
            name: mysql-pass
            key: password
    volumeMounts:
    - name: penyimpanan-abadi
      mountPath: /var/lib/mysql   
  
  volumes:
  - name: penyimpanan-abadi
    persistentVolumeClaim:
      claimName: pvc-mysql-claim  