- name: persiapan node kubernetes (semua node)
  hosts: k8s
  become: yes
  tasks:
    #1. matikan swap
    - name: Matikan swap
      command: swapoff -a

    - name: hapus swab dari /etc/fstab agar permanen
      replace:
        path: /etc/fstab
        regexp: '^([^#].*?\sswap\s+sw\s+.*)$'
        replace: '# \1'
    
    # 2. load kernel modules (Pipa penghubung network)
    - name: Load module kernel overlay dan br_netfilter
      blockinfile:
        path: /etc/modules-load.d/k8s.conf
        create: yes
        block: |
          overlay
          br_netfilter

    - name: Aktifkan module kernel
      shell: |
        modprobe overlay
        modprobe br_netfilter

    # 3. konfigurasi network (Agar Pod bisa ngobrol lintas node)
    - name: Setup sysctl params untuk K8s network
      blockinfile:
        path: /etc/sysctl.d/k8s.conf
        create: yes
        block: |
          net.bridge.bridge-nf-call-iptables  = 1
          net.bridge.bridge-nf-call-ip6tables = 1
          net.ipv4.ip_forward                 = 1

    - name: Apply sysctl params
      command: sysctl --system

    # 4. Install container runtime (Containerd)
    - name: Install dependencies
      apt:
        name: 
          - ca-certificates
          - curl
          - gnupg
        state: present
        update_cache: yes

    - name: Setup Docker repo (untuk containerd)
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg -o /etc/apt/keyrings/docker.asc
        chmod a+r /etc/apt/keyrings/docker.asc
        echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu \
        $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
      args:
        creates: /etc/apt/sources.list.d/docker.list

    - name: Install containerd.io
      apt:
        name: containerd.io
        state: present
        update_cache: yes

    - name: Generate default config containerd
      shell: |
        mkdir -p /etc/containerd
        containerd config default > /etc/containerd/config.toml

    - name: Ubah SystemdCgroup ke true (PENTING untuk K8s stabil)
      replace:
        path: /etc/containerd/config.toml
        regexp: 'SystemdCgroup = false'
        replace: 'SystemdCgroup = true'
    
    - name: Restart containerd
      service:
        name: containerd
        state: restarted
        enabled: yes

    # 5. Install kubernetes Components (Kubeadm, Kubelet, Kubectl)
    - name: Download public signing key Kubernetes
      shell: |
        mkdir -p /etc/apt/keyrings
        curl -fsSL https://pkgs.k8s.io/core:/stable:/v1.30/deb/Release.key | gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg --yes

    - name: Add Kubernetes apt repository
      shell: |
        echo 'deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.30/deb/ /' | tee /etc/apt/sources.list.d/kubernetes.list

    - name: Install Kubeadm, Kubelet, Kubectl
      apt:
        name: 
          - kubelet
          - kubeadm
          - kubectl
        state: present
        update_cache: yes

    - name: Hold versi paket (biar gak ke-update otomatis dan bikin cluster rusak)
      shell: apt-mark hold kubelet kubeadm kubectl